### ISSUE TITLE
January 3rd Presentation Topic

### ISSUE THREAD

**Issue by zachleat** [NebraskaJS/Wiki#1]
Need a topic for the following meetup: http://www.meetup.com/nebraskajs/events/87624182/

@nicknisi has volunteered to speak. @nicknisi should join NebraskaJS on GitHub so that I can pester/assign him with/to this GitHub issue.

Nick has proposed the following topics: Node.js or Backbone.  Other thoughts? Or of these topics, anything specific you're looking for?

Reference tweet: https://twitter.com/mattdsteele/status/267817116290412544

**Comment by nicknisi** [comment]
So, I've been working on a Node.js app with a Backbone/RequireJS frontend for a few months now and would be more than happy to share my experiences.

I could go over some advanced topics service creation, how we manage our callbacks, database connections, and Connect Middleware.

Additionally, or perhaps at a later time, I can talk about RequireJS/AMD and the benefits of writing modular JavaScript.

**Comment by snekse** [comment]
Just RSVPed.

**Comment by markehost** [comment]
I second the motion to present on backbone/underscore.  It's not just a hot topic anymore, it's heavily used in production apps.

Not sure if a Node/Require presentation would be better separately.  These are two big, although, very intertwined topics.

**Comment by mattdsteele** [comment]
For Node, a few things I'd love to see:
- Building services with Express.
- Best practices for avoiding callback hell
- Sharing templates between client-side & server-side JavaScript code. Seems like the holy grail

+1 that Node, Backbone, and Require should each be separate talks.

**Comment by zachleat** [comment]
Yeah, +1 to talks and code that are modular. I think specific topics also have a better chance at giving a variety of skill levels nuggets they can take home.

**Comment by nicknisi** [comment]
For the Jan 3 meetup I'll talk about **Building RESTful services with Node.js** where I'll cover all bullet points brought up by @mattdsteele, along with a few others.

**Comment by zachleat** [comment]
Also, for the record: https://twitter.com/zachleat/status/271257303964061697 referencing https://github.com/jquery/jquery-mobile/pull/5281
