### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by zachleat** [NebraskaJS/Wiki#2]
Assigned to David Kerber: https://twitter.com/davidjkerber/status/268085153283330048

Thanks David!

**Comment by zachleat** [comment]
Just as info, last time we had ~47 signups, 9 pizzas (8 slices each) and 48 sodas. I didn't get an accurate count of people that showed up, but we had 3 pizzas left over and about 15 or 20 sodas left.

**Comment by davekerber** [comment]
Awesome.  Thanks for the info.  I'll be ready for the next one.

**Comment by zachleat** [comment]
Hey Dave, should I say that this is sponsored by Agape Red?

**Comment by davekerber** [comment]
Hi Zach,

You don't have to, but I would really appreciate it if you did.

Thanks,

dave

On Nov 29, 2012, at 1:01 PM, Zach Leatherman notifications@github.com
wrote:

Hey Dave, should I say that this is sponsored by Agape Red?

—
Reply to this email directly or view it on
GitHubhttps://github.com/NebraskaJS/Presentations/issues/2#issuecomment-10861271.

**Comment by zachleat** [comment]
Absolutely—not a problem.

**Comment by zachleat** [comment]
Friendly reminder that this is tomorrow :)

**Comment by davekerber** [comment]
Yep. We are at 50 people right?

On Jan 2, 2013, at 5:56 PM, Zach Leatherman notifications@github.com
wrote:

Friendly reminder that this is tomorrow :)

—
Reply to this email directly or view it on
GitHubhttps://github.com/NebraskaJS/Presentations/issues/2#issuecomment-11829990.

**Comment by zachleat** [comment]
Yep!
