### ISSUE TITLE
What's up with Thursdays?

### ISSUE THREAD

**Issue by jerodsanto** [NebraskaJS/Wiki#3]
The last meetup was switched to a Thursday due to the election. The next meetup is scheduled for a Thursday as well.

I'm hoping that is just because the previous Tuesday is New Year's Day and not a permanent switch.

Is that the case or am I out of luck? (I can't roll on Thursdays)

**Comment by mattdsteele** [comment]
I think @zachleat said the first Tuesday of the month will be the norm.

I hope so, b/c I generally can't roll Thursdays. Because I'm rolling dice then. Because I play D&D. Because JavaScript meetups aren't quite nerdy enough.

**Comment by zachleat** [comment]
Yeah, I figured that New Years Day wouldn't be a good meeting day. We'll have it on Tuesday one of these days.

**Comment by zachleat** [comment]
Oh man, closing as wontfix brings feelings of powerrrrrrr
