### ISSUE TITLE
github as mailing list

### ISSUE THREAD

**Issue by jhannah** [NebraskaJS/Wiki#4]
I'm fascinated by what we seem to be doing: using github as our email mailing list. I haven't seen this done before. I like the Milestone (specific meeting) and Assignment features. I dislike the email subject prefix of [Presentations] -- every time I get an email I think "Presentations? Presentation of what?" I guess I'm on WAY too many email mailing lists. :) 

Anyone else have thoughts?

**Comment by zachleat** [comment]
Ah, my apologies. I was attempting to assign an issue to Nick and added the entire Members team to the Presentations project. I'll create a new Presenters team for this, let me know if you want in on it.

**Comment by jhannah** [comment]
Oh... And here I thought it was a brave new world.  :) :+1:
